[project]
name = "workshop-polars"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "pandas>=2.2.3",
    "polars>=1.26.0",
]

[dependency-groups]
dev = [
    "ipython>=9.0.2",
    "marimo>=0.12.2",
    "notebook>=7.3.3",
]
